/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/COUNTERTitleUsage', 'model/SUSHIReportHeader'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./COUNTERTitleUsage'), require('./SUSHIReportHeader'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.COUNTERTitleReport = factory(root.CounterSushi50Api.ApiClient, root.CounterSushi50Api.COUNTERTitleUsage, root.CounterSushi50Api.SUSHIReportHeader);
  }
}(this, function(ApiClient, COUNTERTitleUsage, SUSHIReportHeader) {
  'use strict';




  /**
   * The COUNTERTitleReport model module.
   * @module model/COUNTERTitleReport
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>COUNTERTitleReport</code>.
   * Describes the formatting needs for the COUNTER Title Report. Response may include the Report_Header (optional), Report_Items (usage stats).
   * @alias module:model/COUNTERTitleReport
   * @class
   * @param reportItems {Array.<module:model/COUNTERTitleUsage>} 
   */
  var exports = function(reportItems) {
    var _this = this;


    _this['Report_Items'] = reportItems;
  };

  /**
   * Constructs a <code>COUNTERTitleReport</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/COUNTERTitleReport} obj Optional instance to populate.
   * @return {module:model/COUNTERTitleReport} The populated <code>COUNTERTitleReport</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Report_Header')) {
        obj['Report_Header'] = SUSHIReportHeader.constructFromObject(data['Report_Header']);
      }
      if (data.hasOwnProperty('Report_Items')) {
        obj['Report_Items'] = ApiClient.convertToType(data['Report_Items'], [COUNTERTitleUsage]);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/SUSHIReportHeader} Report_Header
   */
  exports.prototype['Report_Header'] = undefined;
  /**
   * @member {Array.<module:model/COUNTERTitleUsage>} Report_Items
   */
  exports.prototype['Report_Items'] = undefined;



  return exports;
}));


