/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.COUNTERItemPerformancePeriod = factory(root.CounterSushi50Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The COUNTERItemPerformancePeriod model module.
   * @module model/COUNTERItemPerformancePeriod
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>COUNTERItemPerformancePeriod</code>.
   * @alias module:model/COUNTERItemPerformancePeriod
   * @class
   * @param begin {String} Beginning date for usage in this 'itemPerformance' instance.
   * @param end {String} Ending date for usage in this 'itemPerformance' instance.
   */
  var exports = function(begin, end) {
    var _this = this;

    _this['Begin'] = begin;
    _this['End'] = end;
  };

  /**
   * Constructs a <code>COUNTERItemPerformancePeriod</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/COUNTERItemPerformancePeriod} obj Optional instance to populate.
   * @return {module:model/COUNTERItemPerformancePeriod} The populated <code>COUNTERItemPerformancePeriod</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Begin')) {
        obj['Begin'] = ApiClient.convertToType(data['Begin'], 'String');
      }
      if (data.hasOwnProperty('End')) {
        obj['End'] = ApiClient.convertToType(data['End'], 'String');
      }
    }
    return obj;
  }

  /**
   * Beginning date for usage in this 'itemPerformance' instance.
   * @member {String} Begin
   */
  exports.prototype['Begin'] = undefined;
  /**
   * Ending date for usage in this 'itemPerformance' instance.
   * @member {String} End
   */
  exports.prototype['End'] = undefined;



  return exports;
}));


