/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/COUNTERItemPerformanceInstance', 'model/COUNTERItemPerformancePeriod'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./COUNTERItemPerformanceInstance'), require('./COUNTERItemPerformancePeriod'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.COUNTERItemPerformance = factory(root.CounterSushi50Api.ApiClient, root.CounterSushi50Api.COUNTERItemPerformanceInstance, root.CounterSushi50Api.COUNTERItemPerformancePeriod);
  }
}(this, function(ApiClient, COUNTERItemPerformanceInstance, COUNTERItemPerformancePeriod) {
  'use strict';




  /**
   * The COUNTERItemPerformance model module.
   * @module model/COUNTERItemPerformance
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>COUNTERItemPerformance</code>.
   * @alias module:model/COUNTERItemPerformance
   * @class
   * @param period {Array.<module:model/COUNTERItemPerformancePeriod>} 
   * @param instance {Array.<module:model/COUNTERItemPerformanceInstance>} 
   */
  var exports = function(period, instance) {
    var _this = this;

    _this['Period'] = period;
    _this['Instance'] = instance;
  };

  /**
   * Constructs a <code>COUNTERItemPerformance</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/COUNTERItemPerformance} obj Optional instance to populate.
   * @return {module:model/COUNTERItemPerformance} The populated <code>COUNTERItemPerformance</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Period')) {
        obj['Period'] = ApiClient.convertToType(data['Period'], [COUNTERItemPerformancePeriod]);
      }
      if (data.hasOwnProperty('Instance')) {
        obj['Instance'] = ApiClient.convertToType(data['Instance'], [COUNTERItemPerformanceInstance]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/COUNTERItemPerformancePeriod>} Period
   */
  exports.prototype['Period'] = undefined;
  /**
   * @member {Array.<module:model/COUNTERItemPerformanceInstance>} Instance
   */
  exports.prototype['Instance'] = undefined;



  return exports;
}));


