/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/COUNTERItemPerformance'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./COUNTERItemPerformance'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.COUNTERPlatformUsage = factory(root.CounterSushi50Api.ApiClient, root.CounterSushi50Api.COUNTERItemPerformance);
  }
}(this, function(ApiClient, COUNTERItemPerformance) {
  'use strict';




  /**
   * The COUNTERPlatformUsage model module.
   * @module model/COUNTERPlatformUsage
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>COUNTERPlatformUsage</code>.
   * Defines the output for the Report_Items being returned in a Platform Report.
   * @alias module:model/COUNTERPlatformUsage
   * @class
   * @param platform {String} Name of the platform
   * @param performance {Array.<module:model/COUNTERItemPerformance>} The usage data related to the report item
   */
  var exports = function(platform, performance) {
    var _this = this;

    _this['Platform'] = platform;




    _this['Performance'] = performance;
  };

  /**
   * Constructs a <code>COUNTERPlatformUsage</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/COUNTERPlatformUsage} obj Optional instance to populate.
   * @return {module:model/COUNTERPlatformUsage} The populated <code>COUNTERPlatformUsage</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Platform')) {
        obj['Platform'] = ApiClient.convertToType(data['Platform'], 'String');
      }
      if (data.hasOwnProperty('Data_Type')) {
        obj['Data_Type'] = ApiClient.convertToType(data['Data_Type'], 'String');
      }
      if (data.hasOwnProperty('YOP')) {
        obj['YOP'] = ApiClient.convertToType(data['YOP'], 'String');
      }
      if (data.hasOwnProperty('Access_Type')) {
        obj['Access_Type'] = ApiClient.convertToType(data['Access_Type'], 'String');
      }
      if (data.hasOwnProperty('Access_Method')) {
        obj['Access_Method'] = ApiClient.convertToType(data['Access_Method'], 'String');
      }
      if (data.hasOwnProperty('Performance')) {
        obj['Performance'] = ApiClient.convertToType(data['Performance'], [COUNTERItemPerformance]);
      }
    }
    return obj;
  }

  /**
   * Name of the platform
   * @member {String} Platform
   */
  exports.prototype['Platform'] = undefined;
  /**
   * Nature of the item being reported.
   * @member {module:model/COUNTERPlatformUsage.DataTypeEnum} Data_Type
   */
  exports.prototype['Data_Type'] = undefined;
  /**
   * Year of publication in the format of 'yyyy'.  If the item is available in both online and print format, use the year of publication for the print. Use '0001' for unknown and '9999' for articles in press.
   * @member {String} YOP
   */
  exports.prototype['YOP'] = undefined;
  /**
   * Nature of the access control in place for item retrieved.
   * @member {module:model/COUNTERPlatformUsage.AccessTypeEnum} Access_Type
   */
  exports.prototype['Access_Type'] = undefined;
  /**
   * Identifies if the usage activity was 'Regular' usage (a user doing research on a content site) or if the usage was for the purpose of retrieving content for Text and Data Mining (TDM)
   * @member {module:model/COUNTERPlatformUsage.AccessMethodEnum} Access_Method
   */
  exports.prototype['Access_Method'] = undefined;
  /**
   * The usage data related to the report item
   * @member {Array.<module:model/COUNTERItemPerformance>} Performance
   */
  exports.prototype['Performance'] = undefined;


  /**
   * Allowed values for the <code>Data_Type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.DataTypeEnum = {
    /**
     * value: "Article"
     * @const
     */
    "Article": "Article",
    /**
     * value: "Book"
     * @const
     */
    "Book": "Book",
    /**
     * value: "Book Segment"
     * @const
     */
    "Book Segment": "Book Segment",
    /**
     * value: "Collection"
     * @const
     */
    "Collection": "Collection",
    /**
     * value: "Database"
     * @const
     */
    "Database": "Database",
    /**
     * value: "Dataset"
     * @const
     */
    "Dataset": "Dataset",
    /**
     * value: "Journal"
     * @const
     */
    "Journal": "Journal",
    /**
     * value: "Multimedia"
     * @const
     */
    "Multimedia": "Multimedia",
    /**
     * value: "Platform"
     * @const
     */
    "Platform": "Platform",
    /**
     * value: "Repository Item"
     * @const
     */
    "Repository Item": "Repository Item"  };

  /**
   * Allowed values for the <code>Access_Type</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AccessTypeEnum = {
    /**
     * value: "Controlled"
     * @const
     */
    "Controlled": "Controlled",
    /**
     * value: "OA_Gold"
     * @const
     */
    "OA_Gold": "OA_Gold",
    /**
     * value: "Other_Free_To_Read"
     * @const
     */
    "Other_Free_To_Read": "Other_Free_To_Read"  };

  /**
   * Allowed values for the <code>Access_Method</code> property.
   * @enum {String}
   * @readonly
   */
  exports.AccessMethodEnum = {
    /**
     * value: "Regular"
     * @const
     */
    "Regular": "Regular",
    /**
     * value: "TDM"
     * @const
     */
    "TDM": "TDM"  };


  return exports;
}));


