/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.SUSHIReportList = factory(root.CounterSushi50Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SUSHIReportList model module.
   * @module model/SUSHIReportList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SUSHIReportList</code>.
   * @alias module:model/SUSHIReportList
   * @class
   * @param reportName {String} The long name of the report
   * @param reportID {String} The code, ID or short name of the report that is be used in the request to identify the report.
   * @param release {String} The release or version number of the report.
   * @param reportDescription {String} A short sentence describing the report.
   */
  var exports = function(reportName, reportID, release, reportDescription) {
    var _this = this;

    _this['Report_Name'] = reportName;
    _this['Report_ID'] = reportID;
    _this['Release'] = release;
    _this['Report_Description'] = reportDescription;

  };

  /**
   * Constructs a <code>SUSHIReportList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SUSHIReportList} obj Optional instance to populate.
   * @return {module:model/SUSHIReportList} The populated <code>SUSHIReportList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Report_Name')) {
        obj['Report_Name'] = ApiClient.convertToType(data['Report_Name'], 'String');
      }
      if (data.hasOwnProperty('Report_ID')) {
        obj['Report_ID'] = ApiClient.convertToType(data['Report_ID'], 'String');
      }
      if (data.hasOwnProperty('Release')) {
        obj['Release'] = ApiClient.convertToType(data['Release'], 'String');
      }
      if (data.hasOwnProperty('Report_Description')) {
        obj['Report_Description'] = ApiClient.convertToType(data['Report_Description'], 'String');
      }
      if (data.hasOwnProperty('Path')) {
        obj['Path'] = ApiClient.convertToType(data['Path'], 'String');
      }
    }
    return obj;
  }

  /**
   * The long name of the report
   * @member {String} Report_Name
   */
  exports.prototype['Report_Name'] = undefined;
  /**
   * The code, ID or short name of the report that is be used in the request to identify the report.
   * @member {String} Report_ID
   */
  exports.prototype['Report_ID'] = undefined;
  /**
   * The release or version number of the report.
   * @member {String} Release
   */
  exports.prototype['Release'] = undefined;
  /**
   * A short sentence describing the report.
   * @member {String} Report_Description
   */
  exports.prototype['Report_Description'] = undefined;
  /**
   * The path to use when requesting this report on this service.
   * @member {String} Path
   */
  exports.prototype['Path'] = undefined;



  return exports;
}));


