/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SUSHIErrorModel', 'model/SUSHIOrgIdentifiers', 'model/SUSHIReportHeaderReportAttributes', 'model/SUSHIReportHeaderReportFilters'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SUSHIErrorModel'), require('./SUSHIOrgIdentifiers'), require('./SUSHIReportHeaderReportAttributes'), require('./SUSHIReportHeaderReportFilters'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.SUSHIReportHeader = factory(root.CounterSushi50Api.ApiClient, root.CounterSushi50Api.SUSHIErrorModel, root.CounterSushi50Api.SUSHIOrgIdentifiers, root.CounterSushi50Api.SUSHIReportHeaderReportAttributes, root.CounterSushi50Api.SUSHIReportHeaderReportFilters);
  }
}(this, function(ApiClient, SUSHIErrorModel, SUSHIOrgIdentifiers, SUSHIReportHeaderReportAttributes, SUSHIReportHeaderReportFilters) {
  'use strict';




  /**
   * The SUSHIReportHeader model module.
   * @module model/SUSHIReportHeader
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SUSHIReportHeader</code>.
   * Generalized report header that defines the requested report, the requestor, the customer, filters applied, reportAttributes applied and any exceptions.
   * @alias module:model/SUSHIReportHeader
   * @class
   * @param reportID {String} The report ID or code or shortname. Typically this will be the same code provided in the Report parameter of the request.
   * @param release {String} The release or version of the report.
   * @param reportName {String} The long name of the report.
   */
  var exports = function(reportID, release, reportName) {
    var _this = this;




    _this['Report_ID'] = reportID;
    _this['Release'] = release;
    _this['Report_Name'] = reportName;





  };

  /**
   * Constructs a <code>SUSHIReportHeader</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SUSHIReportHeader} obj Optional instance to populate.
   * @return {module:model/SUSHIReportHeader} The populated <code>SUSHIReportHeader</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Created')) {
        obj['Created'] = ApiClient.convertToType(data['Created'], 'String');
      }
      if (data.hasOwnProperty('Created_By')) {
        obj['Created_By'] = ApiClient.convertToType(data['Created_By'], 'String');
      }
      if (data.hasOwnProperty('Customer_ID')) {
        obj['Customer_ID'] = ApiClient.convertToType(data['Customer_ID'], 'String');
      }
      if (data.hasOwnProperty('Report_ID')) {
        obj['Report_ID'] = ApiClient.convertToType(data['Report_ID'], 'String');
      }
      if (data.hasOwnProperty('Release')) {
        obj['Release'] = ApiClient.convertToType(data['Release'], 'String');
      }
      if (data.hasOwnProperty('Report_Name')) {
        obj['Report_Name'] = ApiClient.convertToType(data['Report_Name'], 'String');
      }
      if (data.hasOwnProperty('Institution_Name')) {
        obj['Institution_Name'] = ApiClient.convertToType(data['Institution_Name'], 'String');
      }
      if (data.hasOwnProperty('Institution_ID')) {
        obj['Institution_ID'] = ApiClient.convertToType(data['Institution_ID'], [SUSHIOrgIdentifiers]);
      }
      if (data.hasOwnProperty('Report_Filters')) {
        obj['Report_Filters'] = ApiClient.convertToType(data['Report_Filters'], [SUSHIReportHeaderReportFilters]);
      }
      if (data.hasOwnProperty('Report_Attributes')) {
        obj['Report_Attributes'] = ApiClient.convertToType(data['Report_Attributes'], [SUSHIReportHeaderReportAttributes]);
      }
      if (data.hasOwnProperty('Exceptions')) {
        obj['Exceptions'] = ApiClient.convertToType(data['Exceptions'], [SUSHIErrorModel]);
      }
    }
    return obj;
  }

  /**
   * Time the report was prepared. Format as defined by date-time - RFC3339
   * @member {String} Created
   */
  exports.prototype['Created'] = undefined;
  /**
   * Name of the organization producing the report.
   * @member {String} Created_By
   */
  exports.prototype['Created_By'] = undefined;
  /**
   * Identifer of the customer the report represents - identifier used on the request
   * @member {String} Customer_ID
   */
  exports.prototype['Customer_ID'] = undefined;
  /**
   * The report ID or code or shortname. Typically this will be the same code provided in the Report parameter of the request.
   * @member {String} Report_ID
   */
  exports.prototype['Report_ID'] = undefined;
  /**
   * The release or version of the report.
   * @member {String} Release
   */
  exports.prototype['Release'] = undefined;
  /**
   * The long name of the report.
   * @member {String} Report_Name
   */
  exports.prototype['Report_Name'] = undefined;
  /**
   * Name of the customer.
   * @member {String} Institution_Name
   */
  exports.prototype['Institution_Name'] = undefined;
  /**
   * Other identifiers for the organization, including ISNI, etc. if available
   * @member {Array.<module:model/SUSHIOrgIdentifiers>} Institution_ID
   */
  exports.prototype['Institution_ID'] = undefined;
  /**
   * A List of report filters used for this report.  Typically  reflect filters provided on the Request.  Filters limit the data to be reported on.
   * @member {Array.<module:model/SUSHIReportHeaderReportFilters>} Report_Filters
   */
  exports.prototype['Report_Filters'] = undefined;
  /**
   * Any additional attributes applied to the report. Attributes inform the level of detail in the report.
   * @member {Array.<module:model/SUSHIReportHeaderReportAttributes>} Report_Attributes
   */
  exports.prototype['Report_Attributes'] = undefined;
  /**
   * Series of exceptions encounted when preparing the report.
   * @member {Array.<module:model/SUSHIErrorModel>} Exceptions
   */
  exports.prototype['Exceptions'] = undefined;



  return exports;
}));


