/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SUSHIOrgIdentifiers'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SUSHIOrgIdentifiers'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.SUSHIConsortiumMemberList = factory(root.CounterSushi50Api.ApiClient, root.CounterSushi50Api.SUSHIOrgIdentifiers);
  }
}(this, function(ApiClient, SUSHIOrgIdentifiers) {
  'use strict';




  /**
   * The SUSHIConsortiumMemberList model module.
   * @module model/SUSHIConsortiumMemberList
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SUSHIConsortiumMemberList</code>.
   * @alias module:model/SUSHIConsortiumMemberList
   * @class
   * @param customerID {String} Identifer for the consortium's member account.  This identifier would be used as the Customer_ID for subsequent report requests for the member.
   * @param name {String} Customer name assigned to the consortium member.
   */
  var exports = function(customerID, name) {
    var _this = this;

    _this['Customer_ID'] = customerID;

    _this['Name'] = name;


  };

  /**
   * Constructs a <code>SUSHIConsortiumMemberList</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SUSHIConsortiumMemberList} obj Optional instance to populate.
   * @return {module:model/SUSHIConsortiumMemberList} The populated <code>SUSHIConsortiumMemberList</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Customer_ID')) {
        obj['Customer_ID'] = ApiClient.convertToType(data['Customer_ID'], 'String');
      }
      if (data.hasOwnProperty('Requestor_ID')) {
        obj['Requestor_ID'] = ApiClient.convertToType(data['Requestor_ID'], 'String');
      }
      if (data.hasOwnProperty('Name')) {
        obj['Name'] = ApiClient.convertToType(data['Name'], 'String');
      }
      if (data.hasOwnProperty('Notes')) {
        obj['Notes'] = ApiClient.convertToType(data['Notes'], 'String');
      }
      if (data.hasOwnProperty('Institution_ID')) {
        obj['Institution_ID'] = ApiClient.convertToType(data['Institution_ID'], [SUSHIOrgIdentifiers]);
      }
    }
    return obj;
  }

  /**
   * Identifer for the consortium's member account.  This identifier would be used as the Customer_ID for subsequent report requests for the member.
   * @member {String} Customer_ID
   */
  exports.prototype['Customer_ID'] = undefined;
  /**
   * The RequestorID to use to retrieve COUNTER stats the consortium's member account -- only include if different from the main consortium's RequestorID.  This identifier would be used as the Requestor for subsequent report requests for the member.
   * @member {String} Requestor_ID
   */
  exports.prototype['Requestor_ID'] = undefined;
  /**
   * Customer name assigned to the consortium member.
   * @member {String} Name
   */
  exports.prototype['Name'] = undefined;
  /**
   * Additional notes regarding the customer.
   * @member {String} Notes
   */
  exports.prototype['Notes'] = undefined;
  /**
   * Other identifiers for the organization, including ISNI, etc. if available
   * @member {Array.<module:model/SUSHIOrgIdentifiers>} Institution_ID
   */
  exports.prototype['Institution_ID'] = undefined;



  return exports;
}));


