/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.SUSHIServiceStatusAlerts = factory(root.CounterSushi50Api.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The SUSHIServiceStatusAlerts model module.
   * @module model/SUSHIServiceStatusAlerts
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SUSHIServiceStatusAlerts</code>.
   * @alias module:model/SUSHIServiceStatusAlerts
   * @class
   */
  var exports = function() {
    var _this = this;



  };

  /**
   * Constructs a <code>SUSHIServiceStatusAlerts</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SUSHIServiceStatusAlerts} obj Optional instance to populate.
   * @return {module:model/SUSHIServiceStatusAlerts} The populated <code>SUSHIServiceStatusAlerts</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('DateTime')) {
        obj['DateTime'] = ApiClient.convertToType(data['DateTime'], 'String');
      }
      if (data.hasOwnProperty('Alert')) {
        obj['Alert'] = ApiClient.convertToType(data['Alert'], 'String');
      }
    }
    return obj;
  }

  /**
   * Date-time of the alert.
   * @member {String} DateTime
   */
  exports.prototype['DateTime'] = undefined;
  /**
   * Text of the alert.
   * @member {String} Alert
   */
  exports.prototype['Alert'] = undefined;



  return exports;
}));


