/**
 * COUNTER_SUSHI5_0 API
 * The COUNTER_SUSHI5_0 API represents a RESTful implementation of SUSHI automation intended to returns COUNTER Release 5 reports and snippets of COUNTER usage in JSON format
 *
 * OpenAPI spec version: 1.0.0
 * Contact: nisohq@niso.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SUSHIServiceStatusAlerts'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SUSHIServiceStatusAlerts'));
  } else {
    // Browser globals (root is window)
    if (!root.CounterSushi50Api) {
      root.CounterSushi50Api = {};
    }
    root.CounterSushi50Api.SUSHIServiceStatus = factory(root.CounterSushi50Api.ApiClient, root.CounterSushi50Api.SUSHIServiceStatusAlerts);
  }
}(this, function(ApiClient, SUSHIServiceStatusAlerts) {
  'use strict';




  /**
   * The SUSHIServiceStatus model module.
   * @module model/SUSHIServiceStatus
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>SUSHIServiceStatus</code>.
   * @alias module:model/SUSHIServiceStatus
   * @class
   * @param serviceActive {Boolean} Indicator if the service is currently able to deliver reports.
   */
  var exports = function(serviceActive) {
    var _this = this;


    _this['ServiceActive'] = serviceActive;



  };

  /**
   * Constructs a <code>SUSHIServiceStatus</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SUSHIServiceStatus} obj Optional instance to populate.
   * @return {module:model/SUSHIServiceStatus} The populated <code>SUSHIServiceStatus</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('Description')) {
        obj['Description'] = ApiClient.convertToType(data['Description'], 'String');
      }
      if (data.hasOwnProperty('ServiceActive')) {
        obj['ServiceActive'] = ApiClient.convertToType(data['ServiceActive'], 'Boolean');
      }
      if (data.hasOwnProperty('RegistryURL')) {
        obj['RegistryURL'] = ApiClient.convertToType(data['RegistryURL'], 'String');
      }
      if (data.hasOwnProperty('Note')) {
        obj['Note'] = ApiClient.convertToType(data['Note'], 'String');
      }
      if (data.hasOwnProperty('Alerts')) {
        obj['Alerts'] = ApiClient.convertToType(data['Alerts'], [SUSHIServiceStatusAlerts]);
      }
    }
    return obj;
  }

  /**
   * Description of the service.
   * @member {String} Description
   */
  exports.prototype['Description'] = undefined;
  /**
   * Indicator if the service is currently able to deliver reports.
   * @member {Boolean} ServiceActive
   */
  exports.prototype['ServiceActive'] = undefined;
  /**
   * If available, the URL separate registy with additional information about the service.
   * @member {String} RegistryURL
   */
  exports.prototype['RegistryURL'] = undefined;
  /**
   * A general note about the service.
   * @member {String} Note
   */
  exports.prototype['Note'] = undefined;
  /**
   * Any alerts related to service interuptions and status.
   * @member {Array.<module:model/SUSHIServiceStatusAlerts>} Alerts
   */
  exports.prototype['Alerts'] = undefined;



  return exports;
}));


